services:
  backend:
    build: ./backend
    container_name: technova-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: technova-frontend
    ports:
      - "8085:80"
    depends_on:
      - backend